### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by ghost** [bakercp/ofxCache#1]
Hi I'm trying to compile the example. I'm using the develop branch

Ubuntu 16.04
OF010

I get the following errors (and some more):

any ideas?

`In file included from /mnt/FILES/CODE/OF/OF_100_64B/addons/ofxCache/libs/ofxCache/include/ofx/Cache/ResourceLoader.h:13:0,
                 from /mnt/FILES/CODE/OF/OF_100_64B/addons/ofxCache/src/ofxCache.h:12,
                 from /mnt/FILES/CODE/OF/OF_100_64B/apps/myApps/xCache-example/src/ofApp.h:12,
                 from /mnt/FILES/CODE/OF/OF_100_64B/apps/myApps/xCache-example/src/main.cpp:8:
/mnt/FILES/CODE/OF/OF_100_64B/addons/ofxCache/libs/ofxCache/include/ofx/Cache/BaseAsyncCache.h:113:53: error: declaration of ‘typedef class ofx::Cache::RequestCompleteArgs<KeyType, ValueType> ofx::Cache::BaseAsyncCache<KeyType, ValueType>::RequestCompleteArgs’ [-fpermissive]
     typedef RequestCompleteArgs<KeyType, ValueType> RequestCompleteArgs;
                                                     ^
/mnt/FILES/CODE/OF/OF_100_64B/addons/ofxCache/libs/ofxCache/include/ofx/Cache/BaseAsyncCache.h:66:7: error: changes meaning of ‘RequestCompleteArgs’ from ‘class ofx::Cache::RequestCompleteArgs<KeyType, ValueType>’ [-fpermissive]
 class RequestCompleteArgs
`

**Comment by bakercp** [comment]
I just fixed a bunch of similar issues 17 days ago here: 56786f977bc6bfb72da04db79d8733f3371af759 do you have the latest version?

**Comment by bakercp** [comment]
I just tested everything on Linux Mint 18/Ubuntu 16.04 and the latest oF release and the tests compiled and ran fine.  I suspect you just need to pull the latest from this repository. Closing now, please re-open if there are still issues.

**Comment by ghost** [comment]
worked now thanks
